services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: medical_store
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pRoot@123"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    image: yuvrajmedical-app
    container_name: yuvraj_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Root@123
      DB_NAME: medical_store
    ports:
      - "8000:5000"
    networks:
      - medical-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static:ro
    networks:
      - medical-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiMWZmNDFmYzFhNDhhNGUxYTY4MjI0MDBhM2M2M2JjYTMiLCJ0IjoiZjRlNDc5N2MtMzIzNi00OGY1LWI1OWItYTM4YjY3ZjE5ZGI4IiwicyI6Ik1EQm1NREE0TW1JdFpUaGlZUzAwTmpVM0xXRXlOVFl0Wm1JME5EQmhObUpoWTJZME5qRmtOakEzWWpZdFpEUmtNUzAwWXpOakxUZzVZVGN0WWpZNE9XTXdNR1U1T0RKaCJ9
    depends_on:
      - nginx
    networks:
      - medical-network

volumes:
  mysql-data:

networks:
  medical-network:
